server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  #    static-path-pattern: /static/**
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      encoding: utf-8
      data-locations:
        classpath:db/data.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#      default_batch_fetch_size: 100
#    open-in-view: true
#    output:
#      ansi:
#        enabled: always
#    jackson:
#      serialization:
#        fail-on-empty-beans: false

#mybatis:
#  mapper-locations:
#    - classpath:mapper/**.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    "[com.tenco.projectinit]": DEBUG
    "[org.hibernate.type]": TRACE
file:
  path: ./images/


sms:
  api:
    key: NCSQUDERFWWWSQ32
    secret: QMEK2AQLFF4IT4WPWULFFOKPGVKQUANS
